# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deparment',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
