# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_scorerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseByYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=255)),
                ('class_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseByYear'),
        ),
    ]
