# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursebyyear_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursebyyear',
            old_name='class_time',
            new_name='room_and_time',
        ),
    ]
