# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20170306_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.TextField(),
        ),
    ]
