# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_comment', '0002_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
