# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_comment', '0003_comment_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score_img',
            field=models.FileField(default='', upload_to='docs/'),
            preserve_default=False,
        ),
    ]
