# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_comment', '0005_comment_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score_img',
            field=models.FileField(null=True, upload_to='docs/'),
        ),
    ]
