# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_comment', '0006_auto_20170122_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='score_img',
        ),
    ]
