# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_comment', '0010_auto_20170129_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='custom_course_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
