# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_page', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('custom_course_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sweety', models.IntegerField(default=0)),
                ('cold', models.IntegerField(default=0)),
                ('hardness', models.IntegerField(default=0)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField()),
                ('score_img', models.FileField(null=True, upload_to='docs/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_page.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
